import { ModelProviderCard } from '@/types/llm';

// Vercel AI Gateway - Unified access to 100+ AI models
// Docs: https://vercel.com/docs/ai-gateway
// API Keys: https://vercel.com/ai-gateway/api-keys
// Models: https://vercel.com/ai-gateway/models
const VercelAIGateway: ModelProviderCard = {
  apiKeyUrl: 'https://vercel.com/dashboard/ai-gateway',
  chatModels: [
    // --- Anthropic Models ---
    {
      contextWindowTokens: 200_000,
      description: 'Claude Opus 4.6 - Mô hình mạnh nhất của Anthropic với 1M context beta, agentic coding xuất sắc',
      displayName: 'Claude Opus 4.6',
      enabled: true,
      functionCall: true,
      id: 'anthropic/claude-opus-4-6',
      maxOutput: 32_000,
      vision: true,
    },
    {
      contextWindowTokens: 200_000,
      description: 'Claude Sonnet 4.6 - Sonnet mạnh nhất, suy luận nâng cao và coding vượt trội',
      displayName: 'Claude Sonnet 4.6',
      enabled: true,
      functionCall: true,
      id: 'anthropic/claude-sonnet-4-6',
      maxOutput: 64_000,
      vision: true,
    },
    {
      contextWindowTokens: 200_000,
      description: 'Claude 4.5 Sonnet - Best balance of intelligence and speed',
      displayName: 'Claude 4.5 Sonnet',
      enabled: true,
      functionCall: true,
      id: 'anthropic/claude-sonnet-4.5',
      maxOutput: 8192,
      vision: true,
    },
    {
      contextWindowTokens: 200_000,
      description: 'Claude 4.5 Haiku - Fast and efficient for simple tasks',
      displayName: 'Claude 4.5 Haiku',
      enabled: true,
      functionCall: true,
      id: 'anthropic/claude-haiku-4.5',
      maxOutput: 8192,
      vision: true,
    },
    // Claude 4 Sonnet/Opus (old IDs) — retired, replaced by 4.6 versions above
    // --- Google Models ---
    {
      contextWindowTokens: 2_000_000,
      description: 'Gemini 3.1 Pro - Suy luận nâng cao, agentic workflows, native multimodal code gen',
      displayName: 'Gemini 3.1 Pro',
      enabled: true,
      functionCall: true,
      id: 'google/gemini-3.1-pro-preview',
      maxOutput: 65_536,
      reasoning: true,
      vision: true,
    },
    {
      contextWindowTokens: 1_000_000,
      description: 'Gemini 3 Flash - Mô hình mới nhất, nhanh, multimodal với Google Search grounding',
      displayName: 'Gemini 3 Flash',
      enabled: true,
      functionCall: true,
      id: 'google/gemini-3-flash',
      maxOutput: 16_384,
      vision: true,
    },
    {
      contextWindowTokens: 1_000_000,
      description: 'Gemini 2.5 Flash - Nhanh với tư duy (thinking mode) và Google Search',
      displayName: 'Gemini 2.5 Flash',
      enabled: true,
      functionCall: true,
      id: 'google/gemini-2.5-flash',
      maxOutput: 65_536,
      reasoning: true,
      vision: true,
    },
    {
      contextWindowTokens: 1_000_000,
      description: 'Gemini 2.5 Flash Lite - Nhẹ, nhanh, tiết kiệm chi phí',
      displayName: 'Gemini 2.5 Flash Lite',
      enabled: true,
      functionCall: true,
      id: 'google/gemini-2.5-flash-lite',
      maxOutput: 8192,
      vision: true,
    },
    {
      contextWindowTokens: 2_000_000,
      description: 'Gemini 2.5 Pro - Suy luận nâng cao với 2M context window',
      displayName: 'Gemini 2.5 Pro',
      enabled: true,
      functionCall: true,
      id: 'google/gemini-2.5-pro',
      maxOutput: 65_536,
      reasoning: true,
      vision: true,
    },
    {
      contextWindowTokens: 1_000_000,
      description: 'Gemini 2.0 Flash - Nhanh và hiệu quả',
      displayName: 'Gemini 2.0 Flash',
      enabled: true,
      functionCall: true,
      id: 'google/gemini-2.0-flash',
      maxOutput: 8192,
      vision: true,
    },
    // --- OpenAI Models ---
    {
      contextWindowTokens: 128_000,
      description: 'GPT-5.3 Codex — Model coding flagship mới nhất của OpenAI, nhanh hơn 25%, tích hợp Codex + GPT-5 training stacks',
      displayName: 'GPT-5.3 Codex',
      enabled: true,
      functionCall: true,
      id: 'openai/gpt-5.3-codex',
      maxOutput: 16_384,
      vision: true,
    },
    {
      contextWindowTokens: 128_000,
      description: 'GPT-5.2 - OpenAI flagship model, mặc định cho ChatGPT',
      displayName: 'GPT-5.2',
      enabled: true,
      functionCall: true,
      id: 'openai/gpt-5.2',
      maxOutput: 16_384,
      vision: true,
    },
    // GPT-4.1 and GPT-4o — retired by OpenAI on Feb 13, 2026
    // --- DeepSeek Models ---
    {
      contextWindowTokens: 128_000,
      description: 'DeepSeek R1 - Advanced reasoning model',
      displayName: 'DeepSeek R1',
      enabled: true,
      id: 'deepseek/deepseek-r1',
      maxOutput: 8192,
      reasoning: true,
    },
    {
      contextWindowTokens: 128_000,
      description: 'DeepSeek V3 - Fast and cost-effective',
      displayName: 'DeepSeek V3',
      enabled: true,
      functionCall: true,
      id: 'deepseek/deepseek-chat',
      maxOutput: 8192,
    },
    // --- xAI Models ---
    {
      contextWindowTokens: 128_000,
      description: 'Grok 4.2 — Kiến trúc 4-agent (Harper, Benjamin, Lucas), giảm 65% hallucination, chuyên gia y khoa & kỹ thuật',
      displayName: 'Grok 4.2',
      enabled: true,
      functionCall: true,
      id: 'xai/grok-4.2',
      maxOutput: 16_384,
      vision: true,
    },
    // --- Moonshot Models ---
    {
      contextWindowTokens: 128_000,
      description: 'Kimi K2.5 — Agent Swarm (100 agents đồng thời), 1T params MoE, multimodal, visual coding xuất sắc',
      displayName: 'Kimi K2.5',
      enabled: true,
      functionCall: true,
      id: 'moonshot/kimi-k2.5',
      maxOutput: 16_384,
      vision: true,
    },
    // --- Meta Models ---
    {
      contextWindowTokens: 128_000,
      description: 'Llama 4 70B - Open-weight large model by Meta',
      displayName: 'Llama 4 70B',
      enabled: true,
      functionCall: true,
      id: 'meta-llama/llama-4-70b-instruct',
      maxOutput: 8192,
    },
  ],
  checkModel: 'google/gemini-3-flash',
  description:
    'Vercel AI Gateway cung cấp quyền truy cập thống nhất vào 100+ mô hình AI từ OpenAI, Anthropic, Google, Meta, xAI và nhiều nhà cung cấp khác. Hỗ trợ auto-fallback, giám sát chi phí, và không markup phí tokens.',
  id: 'vercelaigateway',
  modelList: { showModelFetcher: true },
  modelsUrl: 'https://vercel.com/ai-gateway/models',
  name: 'Vercel AI Gateway',
  settings: {
    disableBrowserRequest: true, // CORS error
    responseAnimation: 'smooth',
    showModelFetcher: true,
  },
  url: 'https://vercel.com/ai-gateway',
};

export default VercelAIGateway;
