/* eslint-disable */
// Chart module guidelines — uses escaped backticks for code fences inside template literal

export const chartModule = {
  category: 'general',
  content: [
    '## Chart Module Guidelines',
    '',
    '### When to Use',
    'Bar, line, pie, doughnut, radar, scatter, bubble, or polar area charts for data comparison and trends.',
    '',
    '### Preferred Library',
    '**Chart.js** (loaded via CDN). Use D3.js only for advanced/custom charts.',
    '',
    '### Template',
    'Use this structure for Chart.js widgets:',
    '- Wrap canvas in a div with max-width for proper sizing',
    '- Load Chart.js from CDN: https://cdn.jsdelivr.net/npm/chart.js',
    '- Create chart with: new Chart(ctx, { type, data, options })',
    '- Set responsive: true, maintainAspectRatio: false',
    '- Read theme colors at runtime:',
    '  var textColor = getComputedStyle(document.documentElement).getPropertyValue("--color-text").trim();',
    '',
    '### Color Palette',
    'Use vibrant, distinguishable colors for datasets:',
    '- rgba(99, 102, 241, 0.7)  — Indigo',
    '- rgba(168, 85, 247, 0.7)  — Purple',
    '- rgba(236, 72, 153, 0.7)  — Pink',
    '- rgba(34, 197, 94, 0.7)   — Green',
    '- rgba(251, 146, 60, 0.7)  — Orange',
    '- rgba(14, 165, 233, 0.7)  — Sky',
    '',
    '### Best Practices',
    '- Always set responsive:true and maintainAspectRatio:false',
    '- Read CSS vars at runtime: getComputedStyle(document.documentElement).getPropertyValue("--color-text")',
    '- Use vibrant, distinguishable colors for datasets (avoid similar hues)',
    '- Include axis labels and units',
    '- Add tooltips for data drill-down',
    '- For comparison charts: use grouped/stacked bars',
    '- For trends: use line charts with point markers',
    '- Wrap canvas in a div with max-width for proper sizing',
    '- Set grid and tick colors: { gridcolor: "var(--color-border)", color: "var(--color-text-secondary)" }',
    '',
    '### Common Mistakes',
    '- Setting colors to hardcoded black/white (invisible in dark/light mode)',
    '- Forgetting responsive:true (chart does not resize)',
    '- Using too many data points without pagination or scrolling',
    '- Not setting canvas parent height (chart collapses to 0)',
    '- Using var(--color-text) in Chart.js options directly — must use getComputedStyle() instead',
  ].join('\n'),
  name: 'chart',
};
